# Generated by Django 3.0.7 on 2020-06-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spam_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
